sudo: required
language: generic

services:
  - docker

script:
  - docker build -t restreamer-helper-bot .
  - docker tag restreamer-helper-bot hancin/restreamer-helper-bot:latest

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
