sudo: required
language: node_js
node_js:
  - "lts/*"
services:
  - docker

before_install:
  - docker build -t hancin/restreamer-helper-bot .

script:
  - echo 1

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
