version: '3.1'

services:

  botproxy:
    container_name: 'botproxy'
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./cfg/production.conf:/etc/nginx/conf.d/default.conf
      - ./cfg/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/restreambot.hancinworld.com/fullchain.pem:/etc/letsencrypt/live/restreambot.hancinworld.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/restreambot.hancinworld.com/privkey.pem:/etc/letsencrypt/live/restreambot.hancinworld.com/privkey.pem
    networks:
      - docker-network
    depends_on:
      - restreambot
    restart: always

  restreambot:
    container_name: 'restreambot'
    image: hancin/restreamer-helper-bot:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./cfg/config.js:/usr/src/app/cfg/config.js
    networks:
      - docker-network
    restart: always
    

networks:
  docker-network:
    driver: bridge